### ISSUE TITLE
融云链接没反应

### ISSUE THREAD

**Issue by Devon3818** [rongcloud/cordova-plugin-rongcloud-im#20]
安卓手机小米5融云init后链接函数失效，没有任何回调，包括错误

**Comment by gdongy** [comment]
问题解决了吗，我也遇到这个问题了，是真么情况啊，谢谢

**Comment by Devon3818** [comment]
好像是停止维护了，而且好像不支持安卓5.0以上版本，最后我用web版的IM，或者可以试下极光推送的IM
